name: Feature and Training Unit and Integration Tests for mlops_stacks_demo
on:
  workflow_dispatch:
  pull_request:
    paths:
      - 'mlops_stacks_demo/**'
      - '.github/workflows/mlops_stacks_demo-run-tests.yml'

defaults:
  run:
    working-directory: ./mlops_stacks_demo/

env:  
  DATABRICKS_HOST: ${{ vars.DATABRICKS_HOST_STAGING }} #STAGING_
  DATABRICKS_CLIENT_ID: ${{ vars.DATABRICKS_CLIENT_ID_STAGING }} #STAGING_
  DATABRICKS_CLIENT_SECRET: ${{ secrets.DATABRICKS_CLIENT_SECRET_STAGING }} #STAGING_
  # DATABRICKS_TOKEN: ${{ secrets.STAGING_WORKSPACE_TOKEN }}

concurrency: mlops_stacks_demo-feature-training-integration-test-staging

jobs:
  unit_tests:
    # runs-on: ubuntu-latest
    runs-on:
      group: databricks-field-eng-protected-runner-group
      labels: ubuntu-latest #ubuntu-20.04 #linux-ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.8
      # Feature store tests bring up a local Spark session, so Java is required.
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'
      - name: Install dependencies
        run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt
            pip install -r ../test-requirements.txt
      - name: Run tests with pytest
        run: |
            pytest

  integration_test:
    needs: unit_tests
    # runs-on: ubuntu-latest
    runs-on:
      group: databricks-field-eng-protected-runner-group
      labels: ubuntu-latest #ubuntu-20.04 #linux-ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - uses: databricks/setup-cli@v0.229.0
      - name: Validate Bundle For Test Deployment Target in Staging Workspace
        id: validate
        run: |
          databricks bundle validate -t mlops_test
      - name: Deploy Bundle to Test Deployment Target in Staging Workspace
        id: deploy
        run: |
          databricks bundle deploy -t mlops_test
      - name: Run Feature Engineering Workflow for Test Deployment Target in Staging Workspace
        id: feature_engineering
        run: |
          databricks bundle run write_feature_table_job -t mlops_test
      - name: Run Training Workflow for Test Deployment Target in Staging Workspace
        id: training
        run: |
          databricks bundle run model_training_job -t mlops_test
