# This GitHub workflow deploys Bundle resources (ML resource config and more)
# defined under mlops_stacks_demo/resources/*
# and mlops_stacks_demo/databricks.yml with staging deployment target configs,
# when PRs are merged into the default branch
name: Bundle Deployment for mlops_stacks_demo Staging

on:
  push:
    branches:
      - 'main'
  workflow_dispatch:

defaults:
  run:
    working-directory: ./mlops_stacks_demo

env:
  DATABRICKS_HOST: ${{ vars.DATABRICKS_HOST_STAGING }} #STAGING_
  DATABRICKS_CLIENT_ID: ${{ vars.DATABRICKS_CLIENT_ID_STAGING }} #STAGING_
  DATABRICKS_CLIENT_SECRET: ${{ secrets.DATABRICKS_CLIENT_SECRET_STAGING }} #STAGING_
  # DATABRICKS_TOKEN: ${{ secrets.STAGING_WORKSPACE_TOKEN }}
  # DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }} #STAGING_
  
jobs:
  staging:
    concurrency: mlops_stacks_demo-staging-bundle-job
    # runs-on: ubuntu-latest
    runs-on:
      group: databricks-field-eng-protected-runner-group
      labels: ubuntu-latest #ubuntu-20.04 #linux-ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: databricks/setup-cli@v0.229.0
      - name: Validate Bundle For Staging
        id: validate
        run: |
          databricks bundle validate -t mlops_staging
      - name: Deploy Bundle to Staging
        id: deploy
        run: |
          databricks bundle deploy -t mlops_staging
